In [1]:
print("hi")

hi


In [1]:
!pip install numpy

In [ ]:
#Tuples are immutable
#Sets have unique elements

In [8]:
#numpy is a way of creating and manipulating arrays
import numpy as np

In [9]:
two_d = np.array([[1, 2], [3,4], [5,6]])
print(two_d)
type(two_d)

[[1 2]
 [3 4]
 [5 6]]


numpy.ndarray

In [10]:
from_range = np.arange(0, 12, 4)
print(from_range)

[0 4 8]


In [14]:
vacuum = np.zeros([2,3,5])
print(vacuum)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [16]:
unity = np.ones(7)
print(unity)

[1. 1. 1. 1. 1. 1. 1.]


In [21]:
fractional_steps = np.linspace(0, 5, 9)
print(fractional_steps)

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375 5.   ]


In [24]:
#creates an identity matrix
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
#syntax is different from zeros
rand = np.random.rand(3, 3)
print(rand)

[[0.00503439 0.95150582 0.43769725]
 [0.9018106  0.36384037 0.22918666]
 [0.62119464 0.37535972 0.47159865]]


In [27]:
# This generates random numbers from a normal distribution
rand_n = np.random.randn(3, 3)
print(rand_n)

[[ 1.04830705  0.26726939 -0.08232913]
 [ 0.94559736  1.10057747 -0.58459916]
 [ 1.08260086  0.2798524   0.0776996 ]]


In [32]:
# upper limit, lower limit, number of random numbers
rand_int = np.random.randint(2,30, 6)
print(rand_int)

[26  6  5 28 10  9]


In [34]:
#the counts and dimensions should fit exactly
rand_int = rand_int.reshape(2,3)
print(rand_int)

[[26  6  5]
 [28 10  9]]


In [35]:
print(rand_int.max())

28


In [36]:
print(rand_int.min())

5


In [38]:
print(rand_int.argmax())

3


In [40]:
print(rand_int.dtype)

int64
